# Generated by Django 5.1.3 on 2025-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_supportticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF Guide"),
                            ("article", "Article"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="help_resources/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
