# Generated by Django 5.1.3 on 2025-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("creator_name", models.CharField(max_length=255)),
                ("creator_description", models.TextField()),
                ("rating", models.FloatField(default=0.0)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.IntegerField()),
                ("total_lectures", models.IntegerField()),
                (
                    "video_lectures",
                    models.FileField(
                        blank=True, null=True, upload_to="courses/videos/"
                    ),
                ),
                (
                    "notes",
                    models.FileField(blank=True, null=True, upload_to="courses/notes/"),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="courses/certificates/"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_percentage", models.FloatField(default=0.0)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("enrolled_students", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
