# Generated by Django 5.1.3 on 2025-02-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_category_remove_course_enrolled_students_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="course",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="course",
            name="video_lectures",
        ),
        migrations.AlterField(
            model_name="note",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="courses.course",
            ),
        ),
        migrations.CreateModel(
            name="VideoLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_file", models.FileField(upload_to="courses/videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_lectures",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Lecture",
        ),
    ]
