# Generated by Django 5.1.3 on 2025-02-23 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_rename_created_at_note_uploaded_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="total_lectures",
        ),
    ]
