# Generated by Django 5.1.3 on 2025-02-23 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_remove_course_total_lectures"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VideoLecture",
            new_name="Lecture",
        ),
    ]
