# Generated by Django 5.1.3 on 2025-02-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_rename_videolecture_lecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="courses.course",
            ),
        ),
    ]
